// GENERATED by scripts/generate-copy-schema.mjs — do not edit.
// Shape mirrors the "article" namespace in messages/en.json.
import { defineField, defineType } from "sanity";

const shape = [
  defineField({
    name: "breadcrumbLabel",
    title: "Breadcrumb Label",
    type: "string",
  }),
  defineField({ name: "home", title: "Home", type: "string" }),
  defineField({ name: "insights", title: "Insights", type: "string" }),
  defineField({ name: "byline", title: "Byline", type: "string" }),
  defineField({ name: "readingTime", title: "Reading Time", type: "string" }),
  defineField({ name: "related", title: "Related", type: "string" }),
  defineField({ name: "viewAll", title: "View All", type: "string" }),
];

export const copyArticle = defineType({
  name: "copyArticle",
  title: "Article furniture",
  type: "document",
  fields: [
    defineField({
      name: "namespace",
      type: "string",
      hidden: true,
      readOnly: true,
      initialValue: "article",
    }),
    defineField({
      name: "translationState",
      title: "Translation bookkeeping",
      type: "text",
      hidden: true,
      readOnly: true,
      description:
        "Written by the Translate action. Records which Spanish strings the machine produced and from which English, so a hand-edited translation is never overwritten.",
    }),
    defineField({
      name: "copy",
      title: "Copy",
      type: "object",
      fields: [
        // collapsible objects rather than field GROUPS: groups are only valid
        // on a document's top-level fields, and these are nested one deep
        // inside `copy`. Sanity does not reject that at schema-validate time —
        // it crashes the structure tool when the form is opened (D-098).
        defineField({
          name: "en",
          title: "English",
          type: "object",
          options: { collapsible: true, collapsed: false },
          fields: shape,
        }),
        defineField({
          name: "es",
          title: "Español",
          type: "object",
          options: { collapsible: true, collapsed: true },
          fields: shape,
        }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "Article furniture" }) },
});
