// GENERATED by scripts/generate-copy-schema.mjs — do not edit.
// Shape mirrors the "ctaBandForClients" namespace in messages/en.json.
import { defineField, defineType } from "sanity";

const shape = [
  defineField({ name: "heading", title: "Heading", type: "string" }),
  defineField({ name: "body", title: "Body", type: "text", rows: 3 }),
  defineField({ name: "cta", title: "Cta", type: "string" }),
  defineField({ name: "secondary", title: "Secondary", type: "string" }),
];

export const copyCtaBandForClients = defineType({
  name: "copyCtaBandForClients",
  title: "CTA band — for clients",
  type: "document",
  fields: [
    defineField({
      name: "namespace",
      type: "string",
      hidden: true,
      readOnly: true,
      initialValue: "ctaBandForClients",
    }),
    defineField({
      name: "translationState",
      title: "Translation bookkeeping",
      type: "text",
      hidden: true,
      readOnly: true,
      description:
        "Written by the Translate action. Records which Spanish strings the machine produced and from which English, so a hand-edited translation is never overwritten.",
    }),
    defineField({
      name: "copy",
      title: "Copy",
      type: "object",
      fields: [
        // collapsible objects rather than field GROUPS: groups are only valid
        // on a document's top-level fields, and these are nested one deep
        // inside `copy`. Sanity does not reject that at schema-validate time —
        // it crashes the structure tool when the form is opened (D-098).
        defineField({
          name: "en",
          title: "English",
          type: "object",
          options: { collapsible: true, collapsed: false },
          fields: shape,
        }),
        defineField({
          name: "es",
          title: "Español",
          type: "object",
          options: { collapsible: true, collapsed: true },
          fields: shape,
        }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "CTA band — for clients" }) },
});
