// GENERATED by scripts/generate-copy-schema.mjs — do not edit.
// Shape mirrors the "forms" namespace in messages/en.json.
import { defineField, defineType } from "sanity";

const shape = [
  defineField({ name: "optional", title: "Optional", type: "string" }),
  defineField({ name: "submitting", title: "Submitting", type: "string" }),
  defineField({
    name: "labels",
    title: "Labels",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({ name: "name", title: "Name", type: "string" }),
      defineField({ name: "email", title: "Email", type: "string" }),
      defineField({ name: "phone", title: "Phone", type: "string" }),
      defineField({ name: "company", title: "Company", type: "string" }),
      defineField({
        name: "currentTitle",
        title: "Current Title",
        type: "string",
      }),
      defineField({
        name: "service",
        title: "Card — what we call it",
        type: "string",
      }),
      defineField({
        name: "clientMessage",
        title: "Client Message",
        type: "string",
      }),
      defineField({
        name: "candidateMessage",
        title: "Candidate Message",
        type: "string",
      }),
    ],
  }),
  defineField({
    name: "services",
    title: "Services",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({
        name: "executive__search",
        title: "Executive-search",
        type: "string",
      }),
      defineField({
        name: "mexico__advisory",
        title: "Mexico-advisory",
        type: "string",
      }),
      defineField({
        name: "leadership__solutions",
        title: "Leadership-solutions",
        type: "string",
      }),
      defineField({ name: "other", title: "Other", type: "string" }),
    ],
  }),
  defineField({
    name: "submit",
    title: "Submit",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({ name: "client", title: "Client", type: "string" }),
      defineField({ name: "candidate", title: "Candidate", type: "string" }),
    ],
  }),
  defineField({
    name: "confidentialNote",
    title: "Confidential Note",
    type: "text",
    rows: 3,
  }),
  defineField({
    name: "errors",
    title: "Errors",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({ name: "name", title: "Name", type: "string" }),
      defineField({ name: "email", title: "Email", type: "string" }),
      defineField({ name: "phone", title: "Phone", type: "string" }),
      defineField({ name: "company", title: "Company", type: "string" }),
      defineField({
        name: "currentTitle",
        title: "Current Title",
        type: "string",
      }),
      defineField({
        name: "service",
        title: "Card — what we call it",
        type: "string",
      }),
      defineField({ name: "message", title: "Message", type: "string" }),
    ],
  }),
  defineField({
    name: "success",
    title: "Message shown when it works",
    description: "The “Thank you — we've got it.” block",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({
        name: "heading",
        title: "Section heading",
        type: "string",
      }),
      defineField({
        name: "clientBody",
        title: "Client Body",
        type: "text",
        rows: 3,
      }),
      defineField({
        name: "candidateBody",
        title: "Candidate Body",
        type: "text",
        rows: 3,
      }),
    ],
  }),
  defineField({
    name: "selectPlaceholder",
    title: "Select Placeholder",
    type: "string",
  }),
];

export const copyForms = defineType({
  name: "copyForms",
  title: "Form labels & messages",
  type: "document",
  fields: [
    defineField({
      name: "namespace",
      type: "string",
      hidden: true,
      readOnly: true,
      initialValue: "forms",
    }),
    defineField({
      name: "translationState",
      title: "Translation bookkeeping",
      type: "text",
      hidden: true,
      readOnly: true,
      description:
        "Written by the Translate action. Records which Spanish strings the machine produced and from which English, so a hand-edited translation is never overwritten.",
    }),
    defineField({
      name: "copy",
      title: "Copy",
      type: "object",
      fields: [
        // collapsible objects rather than field GROUPS: groups are only valid
        // on a document's top-level fields, and these are nested one deep
        // inside `copy`. Sanity does not reject that at schema-validate time —
        // it crashes the structure tool when the form is opened (D-098).
        defineField({
          name: "en",
          title: "English",
          description: "Write the page here. Spanish is generated from it.",
          type: "object",
          options: { collapsible: true, collapsed: false },
          fields: shape,
        }),
        defineField({
          name: "es",
          title: "Español (Spanish)",
          description:
            "Filled in for you. Press “Translate to Spanish” above — you only need to open this to correct a word, and anything you change here is kept forever.",
          type: "object",
          options: { collapsible: true, collapsed: true },
          fields: shape,
        }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "Form labels & messages" }) },
});
