// GENERATED by scripts/generate-copy-schema.mjs — do not edit.
// Shape mirrors the "hero" namespace in messages/en.json.
import { defineField, defineType } from "sanity";

const shape = [
  defineField({ name: "ctaPrimary", title: "Main button", type: "string" }),
  defineField({ name: "ctaSecondary", title: "Second button", type: "string" }),
  defineField({
    name: "regions",
    title: "Small line under the buttons",
    type: "string",
  }),
];

export const copyHero = defineType({
  name: "copyHero",
  title: "Page headers",
  type: "document",
  fields: [
    defineField({
      name: "namespace",
      type: "string",
      hidden: true,
      readOnly: true,
      initialValue: "hero",
    }),
    defineField({
      name: "translationState",
      title: "Translation bookkeeping",
      type: "text",
      hidden: true,
      readOnly: true,
      description:
        "Written by the Translate action. Records which Spanish strings the machine produced and from which English, so a hand-edited translation is never overwritten.",
    }),
    defineField({
      name: "copy",
      title: "Copy",
      type: "object",
      fields: [
        // collapsible objects rather than field GROUPS: groups are only valid
        // on a document's top-level fields, and these are nested one deep
        // inside `copy`. Sanity does not reject that at schema-validate time —
        // it crashes the structure tool when the form is opened (D-098).
        defineField({
          name: "en",
          title: "English",
          description: "Write the page here. Spanish is generated from it.",
          type: "object",
          options: { collapsible: true, collapsed: false },
          fields: shape,
        }),
        defineField({
          name: "es",
          title: "Español (Spanish)",
          description:
            "Filled in for you. Press “Translate to Spanish” above — you only need to open this to correct a word, and anything you change here is kept forever.",
          type: "object",
          options: { collapsible: true, collapsed: true },
          fields: shape,
        }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "Page headers" }) },
});
