// GENERATED by scripts/generate-copy-schema.mjs — do not edit.
// Shape mirrors the "home" namespace in messages/en.json.
import { defineArrayMember, defineField, defineType } from "sanity";

const shape = [
  defineField({
    name: "hero",
    title: "Hero",
    type: "object",
    options: { collapsible: true, collapsed: true },
    fields: [
      defineField({
        name: "headlineLead",
        title: "Headline Lead",
        type: "string",
      }),
      defineField({
        name: "headlineEmphasis",
        title: "Headline Emphasis",
        type: "string",
      }),
      defineField({
        name: "headlineTail",
        title: "Headline Tail",
        type: "string",
      }),
      defineField({ name: "subhead", title: "Subhead", type: "text", rows: 3 }),
      defineField({ name: "ctaPrimary", title: "Cta Primary", type: "string" }),
      defineField({
        name: "ctaSecondary",
        title: "Cta Secondary",
        type: "string",
      }),
      defineField({ name: "regions", title: "Regions", type: "string" }),
    ],
  }),
  defineField({
    name: "chooser",
    title: "Chooser",
    type: "object",
    options: { collapsible: true, collapsed: true },
    fields: [
      defineField({ name: "heading", title: "Heading", type: "string" }),
      defineField({
        name: "cards",
        title: "Cards",
        type: "array",
        of: [
          defineArrayMember({
            type: "object",
            fields: [
              defineField({ name: "need", title: "Need", type: "string" }),
              defineField({
                name: "service",
                title: "Service",
                type: "string",
              }),
              defineField({
                name: "body",
                title: "Body",
                type: "text",
                rows: 3,
              }),
              defineField({ name: "cta", title: "Cta", type: "string" }),
            ],
          }),
        ],
      }),
    ],
  }),
  defineField({
    name: "values",
    title: "Values",
    type: "object",
    options: { collapsible: true, collapsed: true },
    fields: [
      defineField({ name: "heading", title: "Heading", type: "string" }),
      defineField({ name: "body", title: "Body", type: "text", rows: 3 }),
      defineField({
        name: "items",
        title: "Items",
        type: "array",
        of: [
          defineArrayMember({
            type: "object",
            fields: [
              defineField({ name: "title", title: "Title", type: "string" }),
              defineField({ name: "body", title: "Body", type: "string" }),
            ],
          }),
        ],
      }),
    ],
  }),
  defineField({
    name: "stories",
    title: "Stories",
    type: "object",
    options: { collapsible: true, collapsed: true },
    fields: [
      defineField({ name: "heading", title: "Heading", type: "string" }),
      defineField({ name: "viewAll", title: "View All", type: "string" }),
      defineField({ name: "readStory", title: "Read Story", type: "string" }),
      defineField({
        name: "items",
        title: "Items",
        type: "array",
        of: [
          defineArrayMember({
            type: "object",
            fields: [
              defineField({
                name: "category",
                title: "Category",
                type: "string",
              }),
              defineField({ name: "title", title: "Title", type: "string" }),
              defineField({
                name: "body",
                title: "Body",
                type: "text",
                rows: 3,
              }),
              defineField({
                name: "imageAlt",
                title: "Image Alt",
                type: "text",
                rows: 3,
              }),
            ],
          }),
        ],
      }),
    ],
  }),
  defineField({
    name: "quote",
    title: "Quote",
    type: "object",
    options: { collapsible: true, collapsed: true },
    fields: [
      defineField({ name: "lead", title: "Lead", type: "string" }),
      defineField({ name: "emphasis", title: "Emphasis", type: "string" }),
      defineField({ name: "tail", title: "Tail", type: "string" }),
    ],
  }),
  defineField({
    name: "logoWall",
    title: "Logo Wall",
    type: "object",
    options: { collapsible: true, collapsed: true },
    fields: [
      defineField({ name: "eyebrow", title: "Eyebrow", type: "string" }),
    ],
  }),
];

export const copyHome = defineType({
  name: "copyHome",
  title: "Home",
  type: "document",
  fields: [
    defineField({
      name: "namespace",
      type: "string",
      hidden: true,
      readOnly: true,
      initialValue: "home",
    }),
    defineField({
      name: "translationState",
      title: "Translation bookkeeping",
      type: "text",
      hidden: true,
      readOnly: true,
      description:
        "Written by the Translate action. Records which Spanish strings the machine produced and from which English, so a hand-edited translation is never overwritten.",
    }),
    defineField({
      name: "copy",
      title: "Copy",
      type: "object",
      fields: [
        // collapsible objects rather than field GROUPS: groups are only valid
        // on a document's top-level fields, and these are nested one deep
        // inside `copy`. Sanity does not reject that at schema-validate time —
        // it crashes the structure tool when the form is opened (D-098).
        defineField({
          name: "en",
          title: "English",
          type: "object",
          options: { collapsible: true, collapsed: false },
          fields: shape,
        }),
        defineField({
          name: "es",
          title: "Español",
          type: "object",
          options: { collapsible: true, collapsed: true },
          fields: shape,
        }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "Home" }) },
});
