// GENERATED by scripts/generate-copy-schema.mjs — do not edit.
// Shape mirrors the "home" namespace in messages/en.json.
import { defineArrayMember, defineField, defineType } from "sanity";

const shape = [
  defineField({
    name: "hero",
    title: "Top of the page",
    description:
      "The “Critical talent decisions. Better business outcomes.” block",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({
        name: "headlineLead",
        title: "Headline — first part",
        type: "string",
      }),
      defineField({
        name: "headlineEmphasis",
        title: "Headline — the highlighted words",
        type: "string",
      }),
      defineField({
        name: "headlineTail",
        title: "Headline — last part",
        type: "string",
      }),
      defineField({
        name: "subhead",
        title: "Paragraph under the headline",
        type: "text",
        rows: 3,
      }),
      defineField({ name: "ctaPrimary", title: "Main button", type: "string" }),
      defineField({
        name: "ctaSecondary",
        title: "Second button",
        type: "string",
      }),
      defineField({
        name: "regions",
        title: "Small line under the buttons",
        type: "string",
      }),
    ],
  }),
  defineField({
    name: "chooser",
    title: "Choose-your-path cards",
    description: "The “What talent challenge are you facing?” block",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({
        name: "heading",
        title: "Section heading",
        type: "string",
      }),
      defineField({
        name: "cards",
        title: "Cards",
        type: "array",
        of: [
          defineArrayMember({
            type: "object",
            fields: [
              defineField({
                name: "need",
                title: "Card — the problem",
                type: "string",
              }),
              defineField({
                name: "service",
                title: "Card — what we call it",
                type: "string",
              }),
              defineField({
                name: "body",
                title: "Paragraph",
                type: "text",
                rows: 3,
              }),
              defineField({ name: "cta", title: "Button", type: "string" }),
            ],
          }),
        ],
      }),
    ],
  }),
  defineField({
    name: "values",
    title: "What we stand for",
    description: "The “We've sat on your side of the table.” block",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({
        name: "heading",
        title: "Section heading",
        type: "string",
      }),
      defineField({ name: "body", title: "Paragraph", type: "text", rows: 3 }),
      defineField({
        name: "items",
        title: "List items",
        type: "array",
        of: [
          defineArrayMember({
            type: "object",
            fields: [
              defineField({ name: "title", title: "Title", type: "string" }),
              defineField({ name: "body", title: "Paragraph", type: "string" }),
            ],
          }),
        ],
      }),
    ],
  }),
  defineField({
    name: "stories",
    title: "Client stories",
    description: "The “Work that speaks for itself.” block",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({
        name: "heading",
        title: "Section heading",
        type: "string",
      }),
      defineField({
        name: "viewAll",
        title: '"View all" link',
        type: "string",
      }),
      defineField({
        name: "readStory",
        title: '"Read story" link',
        type: "string",
      }),
      defineField({
        name: "items",
        title: "List items",
        type: "array",
        of: [
          defineArrayMember({
            type: "object",
            fields: [
              defineField({
                name: "category",
                title: "Category",
                type: "string",
              }),
              defineField({ name: "title", title: "Title", type: "string" }),
              defineField({
                name: "body",
                title: "Paragraph",
                type: "text",
                rows: 3,
              }),
              defineField({
                name: "imageAlt",
                title: "Image description (for screen readers and Google)",
                type: "text",
                rows: 3,
              }),
            ],
          }),
        ],
      }),
    ],
  }),
  defineField({
    name: "quote",
    title: "Quotation",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({
        name: "lead",
        title: "Opening line (bold)",
        type: "string",
      }),
      defineField({ name: "emphasis", title: "Emphasis", type: "string" }),
      defineField({ name: "tail", title: "Tail", type: "string" }),
    ],
  }),
  defineField({
    name: "logoWall",
    title: "Client logos",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({
        name: "eyebrow",
        title: "Small label above the heading",
        type: "string",
      }),
    ],
  }),
];

export const copyHome = defineType({
  name: "copyHome",
  title: "Home",
  type: "document",
  fields: [
    defineField({
      name: "namespace",
      type: "string",
      hidden: true,
      readOnly: true,
      initialValue: "home",
    }),
    defineField({
      name: "translationState",
      title: "Translation bookkeeping",
      type: "text",
      hidden: true,
      readOnly: true,
      description:
        "Written by the Translate action. Records which Spanish strings the machine produced and from which English, so a hand-edited translation is never overwritten.",
    }),
    defineField({
      name: "copy",
      title: "Copy",
      type: "object",
      fields: [
        // collapsible objects rather than field GROUPS: groups are only valid
        // on a document's top-level fields, and these are nested one deep
        // inside `copy`. Sanity does not reject that at schema-validate time —
        // it crashes the structure tool when the form is opened (D-098).
        defineField({
          name: "en",
          title: "English",
          description: "Write the page here. Spanish is generated from it.",
          type: "object",
          options: { collapsible: true, collapsed: false },
          fields: shape,
        }),
        defineField({
          name: "es",
          title: "Español (Spanish)",
          description:
            "Filled in for you. Press “Translate to Spanish” above — you only need to open this to correct a word, and anything you change here is kept forever.",
          type: "object",
          options: { collapsible: true, collapsed: true },
          fields: shape,
        }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "Home" }) },
});
