// GENERATED by scripts/generate-copy-schema.mjs — do not edit.
import type { SchemaTypeDefinition } from "sanity";
import { copyArticle } from "./article";
import { copyCandidateHelp } from "./candidateHelp";
import { copyCandidateTrust } from "./candidateTrust";
import { copyCandidateValues } from "./candidateValues";
import { copyCaseStudy } from "./caseStudy";
import { copyCtaBand } from "./ctaBand";
import { copyCtaBandCandidates } from "./ctaBandCandidates";
import { copyCtaBandForClients } from "./ctaBandForClients";
import { copyFooter } from "./footer";
import { copyFunctionGrid } from "./functionGrid";
import { copyHero } from "./hero";
import { copyHome } from "./home";
import { copyInsightsIndex } from "./insightsIndex";
import { copyInsightsRow } from "./insightsRow";
import { copyMexicoCase } from "./mexicoCase";
import { copyMexicoEarly } from "./mexicoEarly";
import { copyMexicoQuestions } from "./mexicoQuestions";
import { copyNewsletter } from "./newsletter";
import { copyResultsPage } from "./resultsPage";
import { copySubpageContact } from "./subpage-contact";
import { copySubpageExecutiveSearch } from "./subpage-executiveSearch";
import { copySubpageForCandidates } from "./subpage-forCandidates";
import { copySubpageForClients } from "./subpage-forClients";
import { copySubpageInsights } from "./subpage-insights";
import { copySubpageLeadershipSolutions } from "./subpage-leadershipSolutions";
import { copySubpageMexicoAdvisory } from "./subpage-mexicoAdvisory";
import { copySubpageOpportunities } from "./subpage-opportunities";
import { copySubpageResults } from "./subpage-results";
import { copySubpageSubmitProfile } from "./subpage-submitProfile";
import { copySubpageTalentNetwork } from "./subpage-talentNetwork";
import { copySubpageWhyArsan } from "./subpage-whyArsan";
import { copyTeam } from "./team";
import { copyWhyCall } from "./whyCall";
import { copyWhyChoose } from "./whyChoose";

/**
 * Every page-copy document type, in the order the Studio lists them.
 *
 * STUDIO-ONLY. Importing this from app code pulls all 34 schema modules — and
 * therefore `sanity` — into the server graph, where `swr` resolves to a
 * react-server build with no default export and the build dies pointing at a
 * file nobody wrote. Runtime code wants `./namespaces`, which imports nothing.
 */
export const copyTypes: SchemaTypeDefinition[] = [
  copyHome,
  copySubpageForClients,
  copySubpageExecutiveSearch,
  copySubpageMexicoAdvisory,
  copySubpageLeadershipSolutions,
  copySubpageForCandidates,
  copySubpageResults,
  copySubpageInsights,
  copySubpageWhyArsan,
  copySubpageContact,
  copySubpageOpportunities,
  copySubpageSubmitProfile,
  copySubpageTalentNetwork,
  copyResultsPage,
  copyInsightsIndex,
  copyArticle,
  copyNewsletter,
  copyCtaBand,
  copyCtaBandForClients,
  copyCtaBandCandidates,
  copyInsightsRow,
  copyTeam,
  copyCandidateValues,
  copyCandidateHelp,
  copyCandidateTrust,
  copyWhyChoose,
  copyWhyCall,
  copyFunctionGrid,
  copyMexicoCase,
  copyMexicoQuestions,
  copyMexicoEarly,
  copyCaseStudy,
  copyHero,
  copyFooter,
];
