// GENERATED by scripts/generate-copy-schema.mjs — do not edit.

/**
 * Studio type name → the dotted message namespace it overrides.
 *
 * Deliberately a separate module from `index.ts` with NO imports: this is the
 * half the running site needs, and pulling the schema in beside it would drag
 * the whole Studio into the server bundle (D-097).
 */
export const COPY_NAMESPACES: Record<string, string> = {
  copyHome: "home",
  copySubpageForClients: "subpage.forClients",
  copySubpageExecutiveSearch: "subpage.executiveSearch",
  copySubpageMexicoAdvisory: "subpage.mexicoAdvisory",
  copySubpageLeadershipSolutions: "subpage.leadershipSolutions",
  copySubpageForCandidates: "subpage.forCandidates",
  copySubpageResults: "subpage.results",
  copySubpageInsights: "subpage.insights",
  copySubpageWhyArsan: "subpage.whyArsan",
  copySubpageContact: "subpage.contact",
  copySubpageOpportunities: "subpage.opportunities",
  copySubpageSubmitProfile: "subpage.submitProfile",
  copySubpageTalentNetwork: "subpage.talentNetwork",
  copyResultsPage: "resultsPage",
  copyInsightsIndex: "insightsIndex",
  copyArticle: "article",
  copyNewsletter: "newsletter",
  copyCtaBand: "ctaBand",
  copyCtaBandForClients: "ctaBandForClients",
  copyCtaBandCandidates: "ctaBandCandidates",
  copyInsightsRow: "insightsRow",
  copyTeam: "team",
  copyCandidateValues: "candidateValues",
  copyCandidateHelp: "candidateHelp",
  copyCandidateTrust: "candidateTrust",
  copyWhyChoose: "whyChoose",
  copyWhyCall: "whyCall",
  copyFunctionGrid: "functionGrid",
  copyMexicoCase: "mexicoCase",
  copyMexicoQuestions: "mexicoQuestions",
  copyMexicoEarly: "mexicoEarly",
  copyCaseStudy: "caseStudy",
  copyHero: "hero",
  copyFooter: "footer",
};
