// GENERATED by scripts/generate-copy-schema.mjs — do not edit.

/**
 * Studio type name → the dotted message namespace it overrides.
 *
 * Deliberately a separate module from `index.ts` with NO imports: this is the
 * half the running site needs, and pulling the schema in beside it would drag
 * the whole Studio into the server bundle (D-097).
 */
export const COPY_NAMESPACES: Record<string, string> = {
  copyHome: "home",
  copySubpageForClients: "subpage.forClients",
  copySubpageExecutiveSearch: "subpage.executiveSearch",
  copySubpageMexicoAdvisory: "subpage.mexicoAdvisory",
  copySubpageLeadershipSolutions: "subpage.leadershipSolutions",
  copySubpageForCandidates: "subpage.forCandidates",
  copySubpageResults: "subpage.results",
  copySubpageInsights: "subpage.insights",
  copySubpageWhyArsan: "subpage.whyArsan",
  copySubpageContact: "subpage.contact",
  copySubpageOpportunities: "subpage.opportunities",
  copySubpageOpportunity: "subpage.opportunity",
  copySubpageSubmitProfile: "subpage.submitProfile",
  copySubpageTalentNetwork: "subpage.talentNetwork",
  copyHero: "hero",
  copyCtaBand: "ctaBand",
  copyCtaBandForClients: "ctaBandForClients",
  copyCtaBandCandidates: "ctaBandCandidates",
  copyNewsletter: "newsletter",
  copyTeam: "team",
  copyInsightsRow: "insightsRow",
  copyResultsPage: "resultsPage",
  copyInsightsIndex: "insightsIndex",
  copyArticle: "article",
  copyCaseStudy: "caseStudy",
  copyCandidateValues: "candidateValues",
  copyCandidateHelp: "candidateHelp",
  copyCandidateTrust: "candidateTrust",
  copyWhyChoose: "whyChoose",
  copyWhyCall: "whyCall",
  copyFunctionGrid: "functionGrid",
  copyMexicoCase: "mexicoCase",
  copyMexicoQuestions: "mexicoQuestions",
  copyMexicoEarly: "mexicoEarly",
  copyNav: "nav",
  copyFooter: "footer",
  copyForms: "forms",
  copyErrors: "errors",
  copyArticleCategories: "articleCategories",
  copyMeta: "meta",
  copyBrand: "brand",
};

/**
 * The same list, with the label and the Studio group each belongs under.
 *
 * Three groups, because an editor's question is always one of three: *this
 * page*, *the block that repeats on every page*, or *the whole site*.
 */
export const COPY_PAGES: { type: string; label: string; group: string }[] = [
  { type: "copyHome", label: "Home", group: "Pages" },
  { type: "copySubpageForClients", label: "For Clients", group: "Pages" },
  {
    type: "copySubpageExecutiveSearch",
    label: "Executive Search",
    group: "Pages",
  },
  {
    type: "copySubpageMexicoAdvisory",
    label: "Mexico Advisory",
    group: "Pages",
  },
  {
    type: "copySubpageLeadershipSolutions",
    label: "Leadership Solutions",
    group: "Pages",
  },
  { type: "copySubpageForCandidates", label: "For Candidates", group: "Pages" },
  { type: "copySubpageResults", label: "Results", group: "Pages" },
  { type: "copySubpageInsights", label: "Insights", group: "Pages" },
  { type: "copySubpageWhyArsan", label: "Why ARSAN", group: "Pages" },
  { type: "copySubpageContact", label: "Contact", group: "Pages" },
  {
    type: "copySubpageOpportunities",
    label: "Opportunities (job list)",
    group: "Pages",
  },
  {
    type: "copySubpageOpportunity",
    label: "Opportunities (one job)",
    group: "Pages",
  },
  {
    type: "copySubpageSubmitProfile",
    label: "Submit Your Profile",
    group: "Pages",
  },
  { type: "copySubpageTalentNetwork", label: "Talent Network", group: "Pages" },
  { type: "copyHero", label: "Page headers", group: "Repeated blocks" },
  {
    type: "copyCtaBand",
    label: "“Let’s talk” band — default",
    group: "Repeated blocks",
  },
  {
    type: "copyCtaBandForClients",
    label: "“Let’s talk” band — clients",
    group: "Repeated blocks",
  },
  {
    type: "copyCtaBandCandidates",
    label: "“Let’s talk” band — candidates",
    group: "Repeated blocks",
  },
  {
    type: "copyNewsletter",
    label: "Newsletter sign-up",
    group: "Repeated blocks",
  },
  { type: "copyTeam", label: "Meet the team row", group: "Repeated blocks" },
  {
    type: "copyInsightsRow",
    label: "Latest insights row",
    group: "Repeated blocks",
  },
  {
    type: "copyResultsPage",
    label: "Results page sections",
    group: "Repeated blocks",
  },
  {
    type: "copyInsightsIndex",
    label: "Insights index",
    group: "Repeated blocks",
  },
  {
    type: "copyArticle",
    label: "Article page furniture",
    group: "Repeated blocks",
  },
  {
    type: "copyCaseStudy",
    label: "Case study furniture",
    group: "Repeated blocks",
  },
  {
    type: "copyCandidateValues",
    label: "Candidate values",
    group: "Repeated blocks",
  },
  {
    type: "copyCandidateHelp",
    label: "Candidate help",
    group: "Repeated blocks",
  },
  {
    type: "copyCandidateTrust",
    label: "Candidate trust",
    group: "Repeated blocks",
  },
  {
    type: "copyWhyChoose",
    label: "Why choose ARSAN",
    group: "Repeated blocks",
  },
  { type: "copyWhyCall", label: "Why call", group: "Repeated blocks" },
  {
    type: "copyFunctionGrid",
    label: "Functions we search",
    group: "Repeated blocks",
  },
  { type: "copyMexicoCase", label: "Mexico case", group: "Repeated blocks" },
  {
    type: "copyMexicoQuestions",
    label: "Mexico questions",
    group: "Repeated blocks",
  },
  { type: "copyMexicoEarly", label: "Mexico early", group: "Repeated blocks" },
  { type: "copyNav", label: "Menu & header", group: "Whole site" },
  { type: "copyFooter", label: "Footer", group: "Whole site" },
  { type: "copyForms", label: "Form labels & messages", group: "Whole site" },
  { type: "copyErrors", label: "Error messages", group: "Whole site" },
  {
    type: "copyArticleCategories",
    label: "Article category names",
    group: "Whole site",
  },
  { type: "copyMeta", label: "Site title & description", group: "Whole site" },
  { type: "copyBrand", label: "Company name", group: "Whole site" },
];
