// GENERATED by scripts/generate-copy-schema.mjs — do not edit.
// Shape mirrors the "nav" namespace in messages/en.json.
import { defineField, defineType } from "sanity";

const shape = [
  defineField({ name: "ariaMain", title: "Aria Main", type: "string" }),
  defineField({ name: "cta", title: "Button", type: "string" }),
  defineField({ name: "openMenu", title: "Open Menu", type: "string" }),
  defineField({ name: "close", title: "Close", type: "string" }),
  defineField({
    name: "forClients",
    title: "For Clients",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({ name: "label", title: "Label", type: "string" }),
      defineField({ name: "exploreAll", title: "Explore All", type: "string" }),
      defineField({
        name: "children",
        title: "Children",
        type: "object",
        options: { collapsible: true, collapsed: false },
        fields: [
          defineField({
            name: "executiveSearch",
            title: "Executive Search",
            type: "object",
            options: { collapsible: true, collapsed: false },
            fields: [
              defineField({ name: "label", title: "Label", type: "string" }),
              defineField({
                name: "description",
                title: "Description",
                type: "string",
              }),
            ],
          }),
          defineField({
            name: "mexicoAdvisory",
            title: "Mexico Advisory",
            type: "object",
            options: { collapsible: true, collapsed: false },
            fields: [
              defineField({ name: "label", title: "Label", type: "string" }),
              defineField({
                name: "description",
                title: "Description",
                type: "string",
              }),
            ],
          }),
          defineField({
            name: "leadershipSolutions",
            title: "Leadership Solutions",
            type: "object",
            options: { collapsible: true, collapsed: false },
            fields: [
              defineField({ name: "label", title: "Label", type: "string" }),
              defineField({
                name: "description",
                title: "Description",
                type: "string",
              }),
            ],
          }),
        ],
      }),
      defineField({
        name: "feature",
        title: "Feature",
        description: "The “Have a critical people challenge?” block",
        type: "object",
        options: { collapsible: true, collapsed: false },
        fields: [
          defineField({ name: "title", title: "Title", type: "string" }),
          defineField({ name: "body", title: "Paragraph", type: "string" }),
          defineField({ name: "cta", title: "Button", type: "string" }),
        ],
      }),
    ],
  }),
  defineField({
    name: "forCandidates",
    title: "For Candidates",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({ name: "label", title: "Label", type: "string" }),
      defineField({ name: "exploreAll", title: "Explore All", type: "string" }),
      defineField({
        name: "children",
        title: "Children",
        type: "object",
        options: { collapsible: true, collapsed: false },
        fields: [
          defineField({
            name: "opportunities",
            title: "Opportunities",
            type: "object",
            options: { collapsible: true, collapsed: false },
            fields: [
              defineField({ name: "label", title: "Label", type: "string" }),
              defineField({
                name: "description",
                title: "Description",
                type: "string",
              }),
            ],
          }),
          defineField({
            name: "submitProfile",
            title: "Submit Profile",
            type: "object",
            options: { collapsible: true, collapsed: false },
            fields: [
              defineField({ name: "label", title: "Label", type: "string" }),
              defineField({
                name: "description",
                title: "Description",
                type: "string",
              }),
            ],
          }),
          defineField({
            name: "experience",
            title: "Experience",
            type: "object",
            options: { collapsible: true, collapsed: false },
            fields: [
              defineField({ name: "label", title: "Label", type: "string" }),
              defineField({
                name: "description",
                title: "Description",
                type: "string",
              }),
            ],
          }),
          defineField({
            name: "talentNetwork",
            title: "Talent Network",
            type: "object",
            options: { collapsible: true, collapsed: false },
            fields: [
              defineField({ name: "label", title: "Label", type: "string" }),
              defineField({
                name: "description",
                title: "Description",
                type: "string",
              }),
            ],
          }),
          defineField({
            name: "resources",
            title: "Resources",
            type: "object",
            options: { collapsible: true, collapsed: false },
            fields: [
              defineField({ name: "label", title: "Label", type: "string" }),
              defineField({
                name: "description",
                title: "Description",
                type: "string",
              }),
            ],
          }),
        ],
      }),
      defineField({
        name: "feature",
        title: "Feature",
        description: "The “Your journey is confidential.” block",
        type: "object",
        options: { collapsible: true, collapsed: false },
        fields: [
          defineField({ name: "title", title: "Title", type: "string" }),
          defineField({ name: "body", title: "Paragraph", type: "string" }),
          defineField({ name: "cta", title: "Button", type: "string" }),
        ],
      }),
    ],
  }),
  defineField({
    name: "results",
    title: "Results",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({ name: "label", title: "Label", type: "string" }),
      defineField({ name: "exploreAll", title: "Explore All", type: "string" }),
      defineField({
        name: "children",
        title: "Children",
        type: "object",
        options: { collapsible: true, collapsed: false },
        fields: [
          defineField({
            name: "caseStudies",
            title: "Case Studies",
            type: "object",
            options: { collapsible: true, collapsed: false },
            fields: [
              defineField({ name: "label", title: "Label", type: "string" }),
              defineField({
                name: "description",
                title: "Description",
                type: "string",
              }),
            ],
          }),
          defineField({
            name: "outcomes",
            title: "Outcomes",
            type: "object",
            options: { collapsible: true, collapsed: false },
            fields: [
              defineField({ name: "label", title: "Label", type: "string" }),
              defineField({
                name: "description",
                title: "Description",
                type: "string",
              }),
            ],
          }),
          defineField({
            name: "testimonials",
            title: "Testimonials",
            type: "object",
            options: { collapsible: true, collapsed: false },
            fields: [
              defineField({ name: "label", title: "Label", type: "string" }),
              defineField({
                name: "description",
                title: "Description",
                type: "string",
              }),
            ],
          }),
        ],
      }),
      defineField({
        name: "feature",
        title: "Feature",
        description:
          "The “Before the plant opened, the organization had to be built.” block",
        type: "object",
        options: { collapsible: true, collapsed: false },
        fields: [
          defineField({ name: "title", title: "Title", type: "string" }),
          defineField({ name: "body", title: "Paragraph", type: "string" }),
          defineField({ name: "cta", title: "Button", type: "string" }),
          defineField({
            name: "imageAlt",
            title: "Image description (for screen readers and Google)",
            type: "string",
          }),
        ],
      }),
    ],
  }),
  defineField({
    name: "insights",
    title: "Insights",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({ name: "label", title: "Label", type: "string" }),
      defineField({ name: "exploreAll", title: "Explore All", type: "string" }),
      defineField({
        name: "children",
        title: "Children",
        type: "object",
        options: { collapsible: true, collapsed: false },
        fields: [
          defineField({
            name: "latest",
            title: "Latest",
            type: "object",
            options: { collapsible: true, collapsed: false },
            fields: [
              defineField({ name: "label", title: "Label", type: "string" }),
              defineField({
                name: "description",
                title: "Description",
                type: "string",
              }),
            ],
          }),
          defineField({
            name: "manufacturing",
            title: "Manufacturing",
            type: "object",
            options: { collapsible: true, collapsed: false },
            fields: [
              defineField({ name: "label", title: "Label", type: "string" }),
              defineField({
                name: "description",
                title: "Description",
                type: "string",
              }),
            ],
          }),
          defineField({
            name: "mexico",
            title: "Mexico",
            type: "object",
            options: { collapsible: true, collapsed: false },
            fields: [
              defineField({ name: "label", title: "Label", type: "string" }),
              defineField({
                name: "description",
                title: "Description",
                type: "string",
              }),
            ],
          }),
          defineField({
            name: "reports",
            title: "Reports",
            type: "object",
            options: { collapsible: true, collapsed: false },
            fields: [
              defineField({ name: "label", title: "Label", type: "string" }),
              defineField({
                name: "description",
                title: "Description",
                type: "string",
              }),
            ],
          }),
        ],
      }),
      defineField({
        name: "feature",
        title: "Feature",
        description:
          "The “What manufacturers need to get right about talent now” block",
        type: "object",
        options: { collapsible: true, collapsed: false },
        fields: [
          defineField({ name: "title", title: "Title", type: "string" }),
          defineField({ name: "body", title: "Paragraph", type: "string" }),
          defineField({ name: "cta", title: "Button", type: "string" }),
          defineField({
            name: "imageAlt",
            title: "Image description (for screen readers and Google)",
            type: "string",
          }),
        ],
      }),
    ],
  }),
  defineField({
    name: "whyArsan",
    title: "Why Arsan",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({ name: "label", title: "Label", type: "string" }),
      defineField({ name: "exploreAll", title: "Explore All", type: "string" }),
      defineField({
        name: "children",
        title: "Children",
        type: "object",
        options: { collapsible: true, collapsed: false },
        fields: [
          defineField({
            name: "ourDifference",
            title: "Our Difference",
            type: "object",
            options: { collapsible: true, collapsed: false },
            fields: [
              defineField({ name: "label", title: "Label", type: "string" }),
              defineField({
                name: "description",
                title: "Description",
                type: "string",
              }),
            ],
          }),
          defineField({
            name: "ourPeople",
            title: "Our People",
            type: "object",
            options: { collapsible: true, collapsed: false },
            fields: [
              defineField({ name: "label", title: "Label", type: "string" }),
              defineField({
                name: "description",
                title: "Description",
                type: "string",
              }),
            ],
          }),
          defineField({
            name: "howWeWork",
            title: "How We Work",
            type: "object",
            options: { collapsible: true, collapsed: false },
            fields: [
              defineField({ name: "label", title: "Label", type: "string" }),
              defineField({
                name: "description",
                title: "Description",
                type: "string",
              }),
            ],
          }),
        ],
      }),
      defineField({
        name: "feature",
        title: "Feature",
        description: "The “We've sat on your side of the table.” block",
        type: "object",
        options: { collapsible: true, collapsed: false },
        fields: [
          defineField({ name: "title", title: "Title", type: "string" }),
          defineField({ name: "body", title: "Paragraph", type: "string" }),
          defineField({ name: "cta", title: "Button", type: "string" }),
        ],
      }),
    ],
  }),
  defineField({ name: "ariaLocale", title: "Aria Locale", type: "string" }),
  defineField({
    name: "skipToContent",
    title: "Skip To Content",
    type: "string",
  }),
];

export const copyNav = defineType({
  name: "copyNav",
  title: "Menu & header",
  type: "document",
  fields: [
    defineField({
      name: "namespace",
      type: "string",
      hidden: true,
      readOnly: true,
      initialValue: "nav",
    }),
    defineField({
      name: "translationState",
      title: "Translation bookkeeping",
      type: "text",
      hidden: true,
      readOnly: true,
      description:
        "Written by the Translate action. Records which Spanish strings the machine produced and from which English, so a hand-edited translation is never overwritten.",
    }),
    defineField({
      name: "copy",
      title: "Copy",
      type: "object",
      fields: [
        // collapsible objects rather than field GROUPS: groups are only valid
        // on a document's top-level fields, and these are nested one deep
        // inside `copy`. Sanity does not reject that at schema-validate time —
        // it crashes the structure tool when the form is opened (D-098).
        defineField({
          name: "en",
          title: "English",
          description: "Write the page here. Spanish is generated from it.",
          type: "object",
          options: { collapsible: true, collapsed: false },
          fields: shape,
        }),
        defineField({
          name: "es",
          title: "Español (Spanish)",
          description:
            "Filled in for you. Press “Translate to Spanish” above — you only need to open this to correct a word, and anything you change here is kept forever.",
          type: "object",
          options: { collapsible: true, collapsed: true },
          fields: shape,
        }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "Menu & header" }) },
});
