// GENERATED by scripts/generate-copy-schema.mjs — do not edit.
// Shape mirrors the "resultsPage" namespace in messages/en.json.
import { defineArrayMember, defineField, defineType } from "sanity";

const shape = [
  defineField({
    name: "eyebrow",
    title: "Small label above the heading",
    type: "string",
  }),
  defineField({
    name: "intro",
    title: "Intro paragraph",
    type: "text",
    rows: 3,
  }),
  defineField({ name: "ctaApproach", title: "Cta Approach", type: "string" }),
  defineField({
    name: "stats",
    title: "Stats",
    type: "array",
    of: [
      defineArrayMember({
        type: "object",
        fields: [
          defineField({ name: "figure", title: "Figure", type: "string" }),
          defineField({ name: "label", title: "Label", type: "string" }),
          defineField({ name: "note", title: "Small print", type: "string" }),
        ],
      }),
    ],
  }),
  defineField({
    name: "impact",
    title: "Impact",
    description: "The “Results by area of impact” block",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({
        name: "heading",
        title: "Section heading",
        type: "string",
      }),
      defineField({
        name: "items",
        title: "List items",
        type: "array",
        of: [defineArrayMember({ type: "string" })],
      }),
    ],
  }),
  defineField({
    name: "caseStudies",
    title: "Case Studies",
    description: "The “Case studies that speak for themselves.” block",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({
        name: "heading",
        title: "Section heading",
        type: "string",
      }),
      defineField({
        name: "intro",
        title: "Intro paragraph",
        type: "text",
        rows: 3,
      }),
      defineField({ name: "badge", title: "Badge", type: "string" }),
      defineField({ name: "cta", title: "Button", type: "string" }),
    ],
  }),
  defineField({
    name: "quote",
    title: "Quotation",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({ name: "text", title: "Paragraph", type: "text", rows: 3 }),
      defineField({ name: "name", title: "Name", type: "string" }),
      defineField({
        name: "role",
        title: "Person's job title",
        type: "string",
      }),
      defineField({ name: "org", title: "Company name", type: "string" }),
    ],
  }),
  defineField({
    name: "more",
    title: "More",
    description: "The “More ways we deliver results” block",
    type: "object",
    options: { collapsible: true, collapsed: false },
    fields: [
      defineField({
        name: "heading",
        title: "Section heading",
        type: "string",
      }),
      defineField({
        name: "items",
        title: "List items",
        type: "array",
        of: [
          defineArrayMember({
            type: "object",
            fields: [
              defineField({ name: "title", title: "Title", type: "string" }),
              defineField({ name: "body", title: "Paragraph", type: "string" }),
              defineField({ name: "cta", title: "Button", type: "string" }),
            ],
          }),
        ],
      }),
    ],
  }),
];

export const copyResultsPage = defineType({
  name: "copyResultsPage",
  title: "Results page sections",
  type: "document",
  fields: [
    defineField({
      name: "namespace",
      type: "string",
      hidden: true,
      readOnly: true,
      initialValue: "resultsPage",
    }),
    defineField({
      name: "translationState",
      title: "Translation bookkeeping",
      type: "text",
      hidden: true,
      readOnly: true,
      description:
        "Written by the Translate action. Records which Spanish strings the machine produced and from which English, so a hand-edited translation is never overwritten.",
    }),
    defineField({
      name: "copy",
      title: "Copy",
      type: "object",
      fields: [
        // collapsible objects rather than field GROUPS: groups are only valid
        // on a document's top-level fields, and these are nested one deep
        // inside `copy`. Sanity does not reject that at schema-validate time —
        // it crashes the structure tool when the form is opened (D-098).
        defineField({
          name: "en",
          title: "English",
          description: "Write the page here. Spanish is generated from it.",
          type: "object",
          options: { collapsible: true, collapsed: false },
          fields: shape,
        }),
        defineField({
          name: "es",
          title: "Español (Spanish)",
          description:
            "Filled in for you. Press “Translate to Spanish” above — you only need to open this to correct a word, and anything you change here is kept forever.",
          type: "object",
          options: { collapsible: true, collapsed: true },
          fields: shape,
        }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "Results page sections" }) },
});
