// GENERATED by scripts/generate-copy-schema.mjs — do not edit.
// Shape mirrors the "resultsPage" namespace in messages/en.json.
import { defineArrayMember, defineField, defineType } from "sanity";

const shape = [
  defineField({ name: "eyebrow", title: "Eyebrow", type: "string" }),
  defineField({ name: "intro", title: "Intro", type: "text", rows: 3 }),
  defineField({ name: "ctaApproach", title: "Cta Approach", type: "string" }),
  defineField({
    name: "stats",
    title: "Stats",
    type: "array",
    of: [
      defineArrayMember({
        type: "object",
        fields: [
          defineField({ name: "figure", title: "Figure", type: "string" }),
          defineField({ name: "label", title: "Label", type: "string" }),
          defineField({ name: "note", title: "Note", type: "string" }),
        ],
      }),
    ],
  }),
  defineField({
    name: "impact",
    title: "Impact",
    type: "object",
    options: { collapsible: true, collapsed: true },
    fields: [
      defineField({ name: "heading", title: "Heading", type: "string" }),
      defineField({
        name: "items",
        title: "Items",
        type: "array",
        of: [defineArrayMember({ type: "string" })],
      }),
    ],
  }),
  defineField({
    name: "caseStudies",
    title: "Case Studies",
    type: "object",
    options: { collapsible: true, collapsed: true },
    fields: [
      defineField({ name: "heading", title: "Heading", type: "string" }),
      defineField({ name: "intro", title: "Intro", type: "text", rows: 3 }),
      defineField({ name: "badge", title: "Badge", type: "string" }),
      defineField({ name: "cta", title: "Cta", type: "string" }),
    ],
  }),
  defineField({
    name: "quote",
    title: "Quote",
    type: "object",
    options: { collapsible: true, collapsed: true },
    fields: [
      defineField({ name: "text", title: "Text", type: "text", rows: 3 }),
      defineField({ name: "name", title: "Name", type: "string" }),
      defineField({ name: "role", title: "Role", type: "string" }),
      defineField({ name: "org", title: "Org", type: "string" }),
    ],
  }),
  defineField({
    name: "more",
    title: "More",
    type: "object",
    options: { collapsible: true, collapsed: true },
    fields: [
      defineField({ name: "heading", title: "Heading", type: "string" }),
      defineField({
        name: "items",
        title: "Items",
        type: "array",
        of: [
          defineArrayMember({
            type: "object",
            fields: [
              defineField({ name: "title", title: "Title", type: "string" }),
              defineField({ name: "body", title: "Body", type: "string" }),
              defineField({ name: "cta", title: "Cta", type: "string" }),
            ],
          }),
        ],
      }),
    ],
  }),
];

export const copyResultsPage = defineType({
  name: "copyResultsPage",
  title: "Results — sections",
  type: "document",
  fields: [
    defineField({
      name: "namespace",
      type: "string",
      hidden: true,
      readOnly: true,
      initialValue: "resultsPage",
    }),
    defineField({
      name: "translationState",
      title: "Translation bookkeeping",
      type: "text",
      hidden: true,
      readOnly: true,
      description:
        "Written by the Translate action. Records which Spanish strings the machine produced and from which English, so a hand-edited translation is never overwritten.",
    }),
    defineField({
      name: "copy",
      title: "Copy",
      type: "object",
      fields: [
        // collapsible objects rather than field GROUPS: groups are only valid
        // on a document's top-level fields, and these are nested one deep
        // inside `copy`. Sanity does not reject that at schema-validate time —
        // it crashes the structure tool when the form is opened (D-098).
        defineField({
          name: "en",
          title: "English",
          type: "object",
          options: { collapsible: true, collapsed: false },
          fields: shape,
        }),
        defineField({
          name: "es",
          title: "Español",
          type: "object",
          options: { collapsible: true, collapsed: true },
          fields: shape,
        }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "Results — sections" }) },
});
