// GENERATED by scripts/generate-copy-schema.mjs — do not edit.
// Shape mirrors the "subpage.forCandidates" namespace in messages/en.json.
import { defineArrayMember, defineField, defineType } from "sanity";

const shape = [
  defineField({ name: "title", title: "Title", type: "string" }),
  defineField({
    name: "titleEmphasis",
    title: "Title Emphasis",
    type: "string",
  }),
  defineField({
    name: "intro",
    title: "Intro paragraph",
    type: "text",
    rows: 3,
  }),
  defineField({
    name: "points",
    title: "Points",
    type: "array",
    of: [
      defineArrayMember({
        type: "object",
        fields: [
          defineField({ name: "title", title: "Title", type: "string" }),
          defineField({ name: "body", title: "Paragraph", type: "string" }),
        ],
      }),
    ],
  }),
  defineField({ name: "ctaNote", title: "Cta Note", type: "text", rows: 3 }),
  defineField({ name: "cta", title: "Button", type: "string" }),
  defineField({
    name: "ctaOpportunities",
    title: "Cta Opportunities",
    type: "string",
  }),
  defineField({
    name: "featuredHeading",
    title: "Featured Heading",
    type: "string",
  }),
  defineField({
    name: "featuredViewAll",
    title: "Featured View All",
    type: "string",
  }),
  defineField({
    name: "insightsHeading",
    title: "Insights Heading",
    type: "string",
  }),
  defineField({
    name: "insightsViewAll",
    title: "Insights View All",
    type: "string",
  }),
  defineField({
    name: "networkHeading",
    title: "Network Heading",
    type: "string",
  }),
  defineField({
    name: "networkBody",
    title: "Network Body",
    type: "text",
    rows: 3,
  }),
  defineField({ name: "networkCta", title: "Network Cta", type: "string" }),
  defineField({ name: "heroPrimary", title: "Hero Primary", type: "string" }),
  defineField({
    name: "heroSecondary",
    title: "Hero Secondary",
    type: "string",
  }),
];

export const copySubpageForCandidates = defineType({
  name: "copySubpageForCandidates",
  title: "For Candidates",
  type: "document",
  fields: [
    defineField({
      name: "namespace",
      type: "string",
      hidden: true,
      readOnly: true,
      initialValue: "subpage.forCandidates",
    }),
    defineField({
      name: "translationState",
      title: "Translation bookkeeping",
      type: "text",
      hidden: true,
      readOnly: true,
      description:
        "Written by the Translate action. Records which Spanish strings the machine produced and from which English, so a hand-edited translation is never overwritten.",
    }),
    defineField({
      name: "copy",
      title: "Copy",
      type: "object",
      fields: [
        // collapsible objects rather than field GROUPS: groups are only valid
        // on a document's top-level fields, and these are nested one deep
        // inside `copy`. Sanity does not reject that at schema-validate time —
        // it crashes the structure tool when the form is opened (D-098).
        defineField({
          name: "en",
          title: "English",
          description: "Write the page here. Spanish is generated from it.",
          type: "object",
          options: { collapsible: true, collapsed: false },
          fields: shape,
        }),
        defineField({
          name: "es",
          title: "Español (Spanish)",
          description:
            "Filled in for you. Press “Translate to Spanish” above — you only need to open this to correct a word, and anything you change here is kept forever.",
          type: "object",
          options: { collapsible: true, collapsed: true },
          fields: shape,
        }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "For Candidates" }) },
});
