// GENERATED by scripts/generate-copy-schema.mjs — do not edit.
// Shape mirrors the "subpage.whyArsan" namespace in messages/en.json.
import { defineArrayMember, defineField, defineType } from "sanity";

const shape = [
  defineField({ name: "title", title: "Title", type: "string" }),
  defineField({
    name: "titleEmphasis",
    title: "Title Emphasis",
    type: "string",
  }),
  defineField({ name: "intro", title: "Intro", type: "text", rows: 3 }),
  defineField({
    name: "difference",
    title: "Difference",
    type: "object",
    options: { collapsible: true, collapsed: true },
    fields: [
      defineField({ name: "heading", title: "Heading", type: "string" }),
      defineField({ name: "body", title: "Body", type: "string" }),
      defineField({
        name: "items",
        title: "Items",
        type: "array",
        of: [
          defineArrayMember({
            type: "object",
            fields: [
              defineField({ name: "title", title: "Title", type: "string" }),
              defineField({
                name: "body",
                title: "Body",
                type: "text",
                rows: 3,
              }),
            ],
          }),
        ],
      }),
    ],
  }),
  defineField({
    name: "process",
    title: "Process",
    type: "object",
    options: { collapsible: true, collapsed: true },
    fields: [
      defineField({ name: "heading", title: "Heading", type: "string" }),
      defineField({ name: "body", title: "Body", type: "text", rows: 3 }),
      defineField({
        name: "steps",
        title: "Steps",
        type: "array",
        of: [
          defineArrayMember({
            type: "object",
            fields: [
              defineField({ name: "title", title: "Title", type: "string" }),
              defineField({
                name: "body",
                title: "Body",
                type: "text",
                rows: 3,
              }),
            ],
          }),
        ],
      }),
    ],
  }),
  defineField({
    name: "peopleIntro",
    title: "People Intro",
    type: "text",
    rows: 3,
  }),
];

export const copySubpageWhyArsan = defineType({
  name: "copySubpageWhyArsan",
  title: "Why ARSAN",
  type: "document",
  fields: [
    defineField({
      name: "namespace",
      type: "string",
      hidden: true,
      readOnly: true,
      initialValue: "subpage.whyArsan",
    }),
    defineField({
      name: "translationState",
      title: "Translation bookkeeping",
      type: "text",
      hidden: true,
      readOnly: true,
      description:
        "Written by the Translate action. Records which Spanish strings the machine produced and from which English, so a hand-edited translation is never overwritten.",
    }),
    defineField({
      name: "copy",
      title: "Copy",
      type: "object",
      fields: [
        // collapsible objects rather than field GROUPS: groups are only valid
        // on a document's top-level fields, and these are nested one deep
        // inside `copy`. Sanity does not reject that at schema-validate time —
        // it crashes the structure tool when the form is opened (D-098).
        defineField({
          name: "en",
          title: "English",
          type: "object",
          options: { collapsible: true, collapsed: false },
          fields: shape,
        }),
        defineField({
          name: "es",
          title: "Español",
          type: "object",
          options: { collapsible: true, collapsed: true },
          fields: shape,
        }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "Why ARSAN" }) },
});
