// GENERATED by scripts/generate-copy-schema.mjs — do not edit.
// Shape mirrors the "subpage.opportunities" namespace in messages/en.json.
import { defineArrayMember, defineField, defineType } from "sanity";

const shape = [
  defineField({ name: "title", title: "Title", type: "string" }),
  defineField({
    name: "titleEmphasis",
    title: "Title Emphasis",
    type: "string",
  }),
  defineField({ name: "intro", title: "Intro", type: "text", rows: 3 }),
  defineField({ name: "emptyHeading", title: "Empty Heading", type: "string" }),
  defineField({
    name: "emptyBody",
    title: "Empty Body",
    type: "text",
    rows: 3,
  }),
  defineField({
    name: "emptyCtaNetwork",
    title: "Empty Cta Network",
    type: "string",
  }),
  defineField({
    name: "emptyCtaProfile",
    title: "Empty Cta Profile",
    type: "string",
  }),
  defineField({ name: "eyebrowBadge", title: "Eyebrow Badge", type: "string" }),
  defineField({ name: "searchLabel", title: "Search Label", type: "string" }),
  defineField({
    name: "searchPlaceholder",
    title: "Search Placeholder",
    type: "string",
  }),
  defineField({
    name: "locationLabel",
    title: "Location Label",
    type: "string",
  }),
  defineField({
    name: "functionLabel",
    title: "Function Label",
    type: "string",
  }),
  defineField({ name: "levelLabel", title: "Level Label", type: "string" }),
  defineField({ name: "allLocations", title: "All Locations", type: "string" }),
  defineField({ name: "allFunctions", title: "All Functions", type: "string" }),
  defineField({ name: "allLevels", title: "All Levels", type: "string" }),
  defineField({ name: "searchButton", title: "Search Button", type: "string" }),
  defineField({ name: "clearFilters", title: "Clear Filters", type: "string" }),
  defineField({ name: "showing", title: "Showing", type: "string" }),
  defineField({ name: "sortBy", title: "Sort By", type: "string" }),
  defineField({ name: "sortRecent", title: "Sort Recent", type: "string" }),
  defineField({ name: "sortOldest", title: "Sort Oldest", type: "string" }),
  defineField({ name: "sortTitle", title: "Sort Title", type: "string" }),
  defineField({ name: "isNew", title: "Is New", type: "string" }),
  defineField({ name: "viewDetails", title: "View Details", type: "string" }),
  defineField({
    name: "noMatchHeading",
    title: "No Match Heading",
    type: "string",
  }),
  defineField({
    name: "noMatchBody",
    title: "No Match Body",
    type: "text",
    rows: 3,
  }),
  defineField({
    name: "alertsHeading",
    title: "Alerts Heading",
    type: "string",
  }),
  defineField({ name: "alertsBody", title: "Alerts Body", type: "string" }),
  defineField({ name: "alertsCta", title: "Alerts Cta", type: "string" }),
  defineField({
    name: "refineHeading",
    title: "Refine Heading",
    type: "string",
  }),
  defineField({
    name: "facetEmployment",
    title: "Facet Employment",
    type: "string",
  }),
  defineField({ name: "facetCountry", title: "Facet Country", type: "string" }),
  defineField({ name: "facetFn", title: "Facet Fn", type: "string" }),
  defineField({ name: "facetLevel", title: "Facet Level", type: "string" }),
  defineField({ name: "showMore", title: "Show More", type: "string" }),
  defineField({ name: "showLess", title: "Show Less", type: "string" }),
  defineField({ name: "pagination", title: "Pagination", type: "string" }),
  defineField({ name: "previousPage", title: "Previous Page", type: "string" }),
  defineField({ name: "nextPage", title: "Next Page", type: "string" }),
  defineField({ name: "goToPage", title: "Go To Page", type: "string" }),
  defineField({
    name: "employment",
    title: "Employment",
    type: "object",
    options: { collapsible: true, collapsed: true },
    fields: [
      defineField({ name: "contract", title: "Contract", type: "string" }),
      defineField({ name: "temporary", title: "Temporary", type: "string" }),
    ],
  }),
  defineField({
    name: "level",
    title: "Level",
    type: "object",
    options: { collapsible: true, collapsed: true },
    fields: [
      defineField({ name: "entry", title: "Entry", type: "string" }),
      defineField({ name: "mid", title: "Mid", type: "string" }),
      defineField({ name: "manager", title: "Manager", type: "string" }),
      defineField({ name: "senior", title: "Senior", type: "string" }),
      defineField({ name: "executive", title: "Executive", type: "string" }),
    ],
  }),
  defineField({
    name: "fn",
    title: "Fn",
    type: "object",
    options: { collapsible: true, collapsed: true },
    fields: [
      defineField({ name: "sales", title: "Sales", type: "string" }),
      defineField({ name: "operations", title: "Operations", type: "string" }),
      defineField({
        name: "engineering",
        title: "Engineering",
        type: "string",
      }),
      defineField({ name: "finance", title: "Finance", type: "string" }),
      defineField({ name: "quality", title: "Quality", type: "string" }),
    ],
  }),
  defineField({
    name: "country",
    title: "Country",
    type: "object",
    options: { collapsible: true, collapsed: true },
    fields: [
      defineField({ name: "us", title: "Us", type: "string" }),
      defineField({ name: "mx", title: "Mx", type: "string" }),
    ],
  }),
  defineField({
    name: "workMode",
    title: "Work Mode",
    type: "object",
    options: { collapsible: true, collapsed: true },
    fields: [
      defineField({ name: "onsite", title: "Onsite", type: "string" }),
      defineField({ name: "hybrid", title: "Hybrid", type: "string" }),
      defineField({ name: "remote", title: "Remote", type: "string" }),
    ],
  }),
  defineField({ name: "whyHeading", title: "Why Heading", type: "string" }),
  defineField({
    name: "why",
    title: "Why",
    type: "array",
    of: [
      defineArrayMember({
        type: "object",
        fields: [
          defineField({ name: "title", title: "Title", type: "string" }),
          defineField({ name: "body", title: "Body", type: "string" }),
        ],
      }),
    ],
  }),
  defineField({ name: "closeHeading", title: "Close Heading", type: "string" }),
  defineField({
    name: "closeEmphasis",
    title: "Close Emphasis",
    type: "string",
  }),
  defineField({ name: "closeBody", title: "Close Body", type: "string" }),
  defineField({ name: "closeCta", title: "Close Cta", type: "string" }),
  defineField({
    name: "closeSecondary",
    title: "Close Secondary",
    type: "string",
  }),
  defineField({ name: "postedDays", title: "Posted Days", type: "string" }),
  defineField({ name: "postedWeeks", title: "Posted Weeks", type: "string" }),
];

export const copySubpageOpportunities = defineType({
  name: "copySubpageOpportunities",
  title: "Opportunities",
  type: "document",
  fields: [
    defineField({
      name: "namespace",
      type: "string",
      hidden: true,
      readOnly: true,
      initialValue: "subpage.opportunities",
    }),
    defineField({
      name: "translationState",
      title: "Translation bookkeeping",
      type: "text",
      hidden: true,
      readOnly: true,
      description:
        "Written by the Translate action. Records which Spanish strings the machine produced and from which English, so a hand-edited translation is never overwritten.",
    }),
    defineField({
      name: "copy",
      title: "Copy",
      type: "object",
      fields: [
        // collapsible objects rather than field GROUPS: groups are only valid
        // on a document's top-level fields, and these are nested one deep
        // inside `copy`. Sanity does not reject that at schema-validate time —
        // it crashes the structure tool when the form is opened (D-098).
        defineField({
          name: "en",
          title: "English",
          type: "object",
          options: { collapsible: true, collapsed: false },
          fields: shape,
        }),
        defineField({
          name: "es",
          title: "Español",
          type: "object",
          options: { collapsible: true, collapsed: true },
          fields: shape,
        }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "Opportunities" }) },
});
