// GENERATED by scripts/generate-copy-schema.mjs — do not edit.
// Shape mirrors the "subpage.forClients" namespace in messages/en.json.
import { defineArrayMember, defineField, defineType } from "sanity";

const shape = [
  defineField({ name: "title", title: "Title", type: "string" }),
  defineField({
    name: "titleEmphasis",
    title: "Title Emphasis",
    type: "string",
  }),
  defineField({
    name: "metaTitle",
    title: "Google search result — title",
    type: "string",
  }),
  defineField({
    name: "intro",
    title: "Intro paragraph",
    type: "text",
    rows: 3,
  }),
  defineField({
    name: "heroCtaPrimary",
    title: "Hero Cta Primary",
    type: "string",
  }),
  defineField({ name: "helpHeading", title: "Help Heading", type: "string" }),
  defineField({
    name: "cards",
    title: "Cards",
    type: "array",
    of: [
      defineArrayMember({
        type: "object",
        fields: [
          defineField({ name: "title", title: "Title", type: "string" }),
          defineField({ name: "lede", title: "Lede", type: "string" }),
          defineField({ name: "body", title: "Paragraph", type: "string" }),
          defineField({ name: "cta", title: "Button", type: "string" }),
        ],
      }),
    ],
  }),
  defineField({
    name: "storiesHeading",
    title: "Stories Heading",
    type: "string",
  }),
];

export const copySubpageForClients = defineType({
  name: "copySubpageForClients",
  title: "For Clients",
  type: "document",
  fields: [
    defineField({
      name: "namespace",
      type: "string",
      hidden: true,
      readOnly: true,
      initialValue: "subpage.forClients",
    }),
    defineField({
      name: "translationState",
      title: "Translation bookkeeping",
      type: "text",
      hidden: true,
      readOnly: true,
      description:
        "Written by the Translate action. Records which Spanish strings the machine produced and from which English, so a hand-edited translation is never overwritten.",
    }),
    defineField({
      name: "copy",
      title: "Copy",
      type: "object",
      fields: [
        // collapsible objects rather than field GROUPS: groups are only valid
        // on a document's top-level fields, and these are nested one deep
        // inside `copy`. Sanity does not reject that at schema-validate time —
        // it crashes the structure tool when the form is opened (D-098).
        defineField({
          name: "en",
          title: "English",
          description: "Write the page here. Spanish is generated from it.",
          type: "object",
          options: { collapsible: true, collapsed: false },
          fields: shape,
        }),
        defineField({
          name: "es",
          title: "Español (Spanish)",
          description:
            "Filled in for you. Press “Translate to Spanish” above — you only need to open this to correct a word, and anything you change here is kept forever.",
          type: "object",
          options: { collapsible: true, collapsed: true },
          fields: shape,
        }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "For Clients" }) },
});
