// GENERATED by scripts/generate-copy-schema.mjs — do not edit.
// Shape mirrors the "subpage.opportunity" namespace in messages/en.json.
import { defineArrayMember, defineField, defineType } from "sanity";

const shape = [
  defineField({
    name: "eyebrow",
    title: "Small label above the heading",
    type: "string",
  }),
  defineField({ name: "breadcrumb", title: "Breadcrumb", type: "string" }),
  defineField({ name: "aboutHeading", title: "About Heading", type: "string" }),
  defineField({ name: "nextHeading", title: "Next Heading", type: "string" }),
  defineField({
    name: "next",
    title: "Next",
    type: "array",
    of: [
      defineArrayMember({
        type: "object",
        fields: [
          defineField({ name: "title", title: "Title", type: "string" }),
          defineField({
            name: "body",
            title: "Paragraph",
            type: "text",
            rows: 3,
          }),
        ],
      }),
    ],
  }),
  defineField({
    name: "detailsHeading",
    title: "Details Heading",
    type: "string",
  }),
  defineField({
    name: "labelLocation",
    title: "Label Location",
    type: "string",
  }),
  defineField({
    name: "labelEmployment",
    title: "Label Employment",
    type: "string",
  }),
  defineField({ name: "labelLevel", title: "Label Level", type: "string" }),
  defineField({
    name: "labelFunction",
    title: "Label Function",
    type: "string",
  }),
  defineField({ name: "labelPosted", title: "Label Posted", type: "string" }),
  defineField({ name: "apply", title: "Apply", type: "string" }),
  defineField({ name: "backToBoard", title: "Back To Board", type: "string" }),
  defineField({
    name: "similarHeading",
    title: "Similar Heading",
    type: "string",
  }),
  defineField({
    name: "confidentialNote",
    title: "Confidential Note",
    type: "text",
    rows: 3,
  }),
  defineField({ name: "crumbHome", title: "Crumb Home", type: "string" }),
  defineField({ name: "crumbBoard", title: "Crumb Board", type: "string" }),
];

export const copySubpageOpportunity = defineType({
  name: "copySubpageOpportunity",
  title: "Opportunities (one job)",
  type: "document",
  fields: [
    defineField({
      name: "namespace",
      type: "string",
      hidden: true,
      readOnly: true,
      initialValue: "subpage.opportunity",
    }),
    defineField({
      name: "translationState",
      title: "Translation bookkeeping",
      type: "text",
      hidden: true,
      readOnly: true,
      description:
        "Written by the Translate action. Records which Spanish strings the machine produced and from which English, so a hand-edited translation is never overwritten.",
    }),
    defineField({
      name: "copy",
      title: "Copy",
      type: "object",
      fields: [
        // collapsible objects rather than field GROUPS: groups are only valid
        // on a document's top-level fields, and these are nested one deep
        // inside `copy`. Sanity does not reject that at schema-validate time —
        // it crashes the structure tool when the form is opened (D-098).
        defineField({
          name: "en",
          title: "English",
          description: "Write the page here. Spanish is generated from it.",
          type: "object",
          options: { collapsible: true, collapsed: false },
          fields: shape,
        }),
        defineField({
          name: "es",
          title: "Español (Spanish)",
          description:
            "Filled in for you. Press “Translate to Spanish” above — you only need to open this to correct a word, and anything you change here is kept forever.",
          type: "object",
          options: { collapsible: true, collapsed: true },
          fields: shape,
        }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "Opportunities (one job)" }) },
});
